services:
  - type: web
    name: ani-creator-bot
    env: python
    buildCommand: ""
    startCommand: python cognitio_main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: TON_TOKEN_TELEGRAM
      - key: OPENAI_API_KEY
        value: TA_CLE_OPENAI
